# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97b77611cbf111c999185522b203040dbc80c50d1626a718d65756054b153253020d05aa52c85a7d5c7e06981f8c382f6b91231a0312b15bdd9fc9986abff5bb

test:
  secret_key_base: b152b099d3ba63c6a203bc1cce5e9c245c0553e6b9e4295f02746e28d3240247c826ae453c44e8881ec151be26a35cc450899a39700c89fe2a9975fdedeb49a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
